homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat_home
  longitude: !secret long_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elev_home
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz_home
  # Customizations
  customize: !include customize.yaml

frontend:
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
updater:
discovery:
conversation:
history:
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

# Media
media_player:
  - platform: plex

# Lights
light:
  platform: hue
  host: !secret hue_bridge_ip

# Custom Panels
# panel_iframe:
#   router:
#     title: 'Router'
#     url: 'http://192.168.1.1'
#     icon: mdi:access-point-network

# Groups
group: !include groups.yaml

# Automations
automation: !include automation.yaml

# Z-Wave
zwave:
  usb_path: /dev/zwave
  config_path: /srv/hass/python-openzwave/openzwave/config
